language: generic

sudo: required

services:
  - docker

before_script:
  - cat docker/postgres.tar | docker import - busybox_import

script:
  - docker build -t test/postgres .

after_script:
  - docker export test/postgres > docker/postgres.tar

cache:
  directories:
    - docker
